# Generated by Django 2.1.5 on 2019-01-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='color',
            field=models.CharField(default='cyan darken-1', max_length=30),
        ),
    ]
